[package]
name = "noise-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "noise"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
noise-client = { path = "../noise-client" }
tokio.workspace = true
